// Beginner-readable copy for the "stack, explained" cards. One entry per tool:
// what it is, the one job it does here, and why it matters. No assumed knowledge.
export const STACK = [
  { name: 'Docker', what: 'Packages an app and everything it needs into a portable image.',
    job: 'Builds the API and web images so they run identically everywhere.',
    why: 'Eliminates "works on my machine" — the same image runs in CI and in the cluster.' },
  { name: 'GitHub Actions', what: 'Runs automated workflows when you push code.',
    job: 'Builds, tests, and scans each image on every change, then pushes it.',
    why: 'Catches problems automatically before anything ships — continuous integration.' },
  { name: 'Trivy', what: 'Scans container images for known security vulnerabilities.',
    job: 'Fails the pipeline if the image has HIGH/CRITICAL CVEs.',
    why: 'Finds security issues early, in the pipeline, not in production ("shift-left").' },
  { name: 'GHCR', what: "GitHub's container registry — storage for built images.",
    job: 'Holds every image, tagged with the exact commit it was built from.',
    why: 'A traceable, versioned home for images the cluster pulls from.' },
  { name: 'Helm', what: 'A package manager for Kubernetes. Instead of hand-writing raw YAML for every resource, you write reusable templated charts and fill in the variables at install time.',
    job: 'Bundles each service’s Deployment, Service, and Ingress into one chart whose image tag is a single value the CD step swaps on every release.',
    why: 'That one swappable tag is what makes GitOps possible — changing it in Git becomes the entire deploy. The same chart targets different environments just by changing values, not by duplicating YAML.' },
  { name: 'k3s', what: 'A lightweight Kubernetes distribution.',
    job: 'Runs the cluster locally that actually hosts the services.',
    why: 'Real Kubernetes on a laptop — no cloud bill — to learn the real mechanics.' },
  { name: 'ArgoCD', what: 'A GitOps continuous-delivery controller that runs inside the cluster and treats a Git repo as the source of truth for what should be deployed.',
    job: 'Continuously watches the Helm charts in the repo; when the committed image tag changes, it pulls the new image and reconciles the cluster’s real state to match the desired state in Git.',
    why: 'Nobody runs kubectl or helm by hand — you change Git and the cluster converges on its own. Deploys become automatic, auditable, and trivially reversible: just revert the commit.' },
]
